version: '3.8'
services:
    mysql:
      image: mysql:8
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: mininetumo
      ports:
        - "3306:3306"
      volumes:
        - mysql-data:/var/lib/mysql
      networks:
        - mininetumo-network
    redis:
      image: redis:6
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      networks:
        - mininetumo-network
    backend:
      build:
        context: ../backend
      ports:
        - "5000:5000"
      volumes:
        - ../backend:/app
      depends_on:
        - mysql
        - redis
      networks:
        - mininetumo-network
      environment:
        - MYSQL_HOST=mysql
        - MYSQL_USER=root
        - MYSQL_PASSWORD=
        - MYSQL_DATABASE=mininetumo
        - CELERY_BROKER_URL=redis://redis:6379/0
        - JWT_SECRET_KEY=your-secret-key
        - SLACK_WEBHOOK_URL=your-slack-webhook
        - MAILTRAP_USERNAME=your-mailtrap-username
        - MAILTRAP_PASSWORD=your-mailtrap-password
    worker:
      build:
        context: ../backend
      command: celery -A worker.tasks worker --loglevel=info
      depends_on:
        - redis
      networks:
        - mininetumo-network
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
volumes:
    mysql-data:
    redis-data:
networks:
    mininetumo-network:
      driver: bridge